# Generated by Django 3.2.7 on 2021-12-20 04:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=30, verbose_name='Tên Người đăng: ')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Tiêu đề')),
                ('date', models.DateTimeField(verbose_name='thời gian đăng')),
                ('demo', models.TextField(default='', verbose_name='Bản giới thiệu')),
                ('content', ckeditor.fields.RichTextField(verbose_name='nội dung')),
                ('link', models.CharField(max_length=100000, verbose_name='Link nguồn')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-id'],
            },
        ),
    ]
