# Generated by Django 3.2.7 on 2021-12-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Họ tên: ')),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='Số điện thoại: ')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email: ')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='Tiêu đề')),
                ('message', models.TextField(null=True, verbose_name='Nội dung')),
            ],
        ),
    ]
