# Generated by Django 3.2.7 on 2021-12-20 04:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Câu Hỏi: ')),
                ('answer', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Câu trả lời: ')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceBook', models.CharField(default='', max_length=1000, verbose_name='Facebook')),
                ('twitter', models.CharField(default='', max_length=1000, verbose_name='Facebook')),
                ('instagram', models.CharField(default='', max_length=1000, verbose_name='Facebook')),
            ],
            options={
                'db_table': 'social',
            },
        ),
        migrations.CreateModel(
            name='whyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Tiêu đề: ')),
                ('detail', models.TextField(default='', verbose_name='Chi tiết: ')),
            ],
            options={
                'db_table': 'why Choose Us',
            },
        ),
    ]
