# Generated by Django 3.2.7 on 2021-12-20 04:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Tiêu đề')),
                ('date', models.DateField(verbose_name='Thời điểm')),
                ('event', models.TextField(default='', max_length=100000, verbose_name='Sự kiện')),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50, verbose_name='Họ')),
                ('lastName', models.CharField(default='', max_length=50, verbose_name='Tên')),
                ('position', models.CharField(default='', max_length=20, verbose_name='Chức vụ')),
                ('phoneNumber', models.CharField(default='', max_length=11, null=True, verbose_name='Số điện thoại')),
                ('email', models.CharField(default='', max_length=100, null=True, verbose_name='email')),
                ('address', models.CharField(default='', max_length=200, null=True, verbose_name='Địa chỉ')),
                ('birth_date', models.DateField(null=True, verbose_name='Ngày sinh')),
                ('descriptions', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Giới thiệu')),
                ('avata', models.ImageField(null=True, upload_to='', verbose_name='Ảnh đại diện')),
            ],
        ),
        migrations.CreateModel(
            name='local_info',
            fields=[
                ('info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.info')),
            ],
            bases=('about.info',),
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.info')),
                ('faceBook', models.CharField(default='', max_length=1000, verbose_name='Facebook')),
                ('twitter', models.CharField(default='', max_length=1000, verbose_name='Facebook')),
                ('instagram', models.CharField(default='', max_length=1000, verbose_name='Facebook')),
            ],
            bases=('about.info',),
        ),
    ]
